version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - '.:/product-register'
    tty: true
    stdin_open: true
   
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    enviroment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'       
